name: Test Deploy

on:
  workflow_dispatch:
  
jobs:
  build-test-branch:
    name: "Build and Test Of PR"

    runs-on: ubuntu-latest

    steps:

# THIS LINE SHOULD BE COMMENTED OUT AT BEGINNING OF DEMO
#    - name: Make PR Fail
#      run: exit 1

    - uses: actions/checkout@v2
      
    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Install dependencies
      run: dotnet restore "${{ github.workspace }}/mywebapp/mywebapp.sln"
    
    - name: Build
      run: dotnet build "${{ github.workspace }}/mywebapp/mywebapp.sln" --configuration Release --no-restore
    
    - name: Test
      run: dotnet test "${{ github.workspace }}/mywebapp/mywebapp.sln" --no-restore --verbosity normal
      
    - name: Publish
      run: |
        dotnet publish "${{ github.workspace }}/mywebapp/src/mywebapp.csproj" -c Release -o mywebapp
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: mywebappbuildartifacts
        # A file, directory or wildcard pattern that describes what to upload
        path: mywebapp/**
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error
        # Duration after which artifact will expire in days. 0 means using default retention.
        retention-days: 90
  
  